version: "3.3"
services:
  frontend:
    build:
      context: ../react-client-application # Path to your react code
    image: frontend
    container_name: frontend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000" # Map port 2200 on the host to port 2200 in the container
    environment:
      - NODE_ENV=production
    command: node server.js # Adjust this based on your Node.js entry point
  backend:
    build:
      context: ../apps/server # Path to your Node.js API code
    image: api
    container_name: backend
    restart: always
    depends_on:
      - db
    ports:
      - "2200:2200" # Map port 2200 on the host to port 2200 in the container
    environment:
      - NODE_ENV=production
    command: node index.js # Adjust this based on your Node.js entry point
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose port 80 for the reverse proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount your Nginx config
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d/:ro"
volumes:
  my-db:
